create database CaseStudy1

select * from customer
select * from prod_cat_info
select * from transactions


--DATA PREPARATION AND UNDERSTANDING  

--1. What is the total number of rows in each of the 3 tables in the database?

select COUNT(*)[No. of rows],'Customer' [Table] from Customer
union all
select COUNT(*),'prod_cat_info' from prod_cat_info
union all
select count(*),'Transactions' from Transactions

--2. What is the total number of transactions that have a return?

select COUNT(*)[Total no. of return transactions] from [Transactions]
where qty < 0

--3. As you would have noticed, the dates provided across the datasets are not in a correct format. As first steps, pls convert the date variables into valid date formats before proceeding ahead. 

select CONVERT(datetime,tran_date,105) [DATE]
from Transactions

--4. What is the time range of the transaction data available for analysis? Show the  output in number of days, months and years simultaneously in different columns.      

select DATEDIFF(DAY,CONVERT(datetime,(min(tran_date)),103),max(tran_date)) [day], DATEDIFF(MONTH,CONVERT(datetime,(min(tran_date)),103), max(tran_date)) [month], DATEDIFF(YEAR,CONVERT(datetime,(min(tran_date)),103), max(tran_date)) [year] from transactions 

--5. Which product category does the sub-category “DIY” belong to?  

select prod_cat, prod_subcat from prod_cat_info
where prod_subcat = 'DIY'


--DATA ANALYSIS

--1. Which channel is most frequently used for transactions?  

select top 1 store_type, count(store_type) [No. of transaction] from Transactions
group by Store_type
order by [No. of transaction] desc

--2. What is the count of Male and Female customers in the database? 

select gender,count (*)[Total count]
from Customer
where gender = 'M' or Gender = 'F'
group by gender 
order by [Total count] desc


--3. From which city do we have the maximum number of customers and how many?  

select top 1 city_code,count(city_code)[No. of customers] from Customer
group by city_code
order by [No. of customers] desc

--4. How many sub-categories are there under the Books category?  

select prod_cat, COUNT(*)[Total Sub-categories] from prod_cat_info
where prod_cat = 'Books'
group by prod_cat
order by [Total Sub-categories]desc

--5. What is the maximum quantity of products ever ordered?  

select max(qty)[Max qty] from Transactions
--OR
select top 1 qty from Transactions
where qty > 0

--6. What is the net total revenue generated in categories Electronics & books?  

Select SUM(cast(total_amt as float)) [total revenue]  from Transactions as t left join prod_cat_info as p on t.prod_cat_code=p.prod_cat_code and t.prod_subcat_code=p.prod_sub_cat_code
where prod_cat in ('Electronics' , 'books')


--7. How many customers have >10 transactions with us, excluding returns? 

select cust_id, COUNT(transaction_id) [Count] from Transactions
where Qty > 0
group by cust_id
having COUNT(transaction_id) > 10 

--8. What is the combined revenue earned from the “Electronics” & “Clothing”  categories, from “Flagship stores”?  

select sum(cast(total_amt as float)) [Total revenue] from Transactions as t left join prod_cat_info as p on t.prod_cat_code=p.prod_cat_code and t.prod_subcat_code=p.prod_sub_cat_code
where prod_cat in ('Electronics' , 'Clothing') and Store_type = 'Flagship Store'

--9. What is the total revenue generated from “Male” customers in “Electronics”  category? Output should display total revenue by prod sub-cat.  

select * from prod_cat_info
select * from customer 
select * from transactions

select Gender,prod_cat,prod_subcat,sum(cast(total_amt as float)) [Total revenue] from Customer as c left join Transactions as t 
on c.customer_Id=t.cust_id left join prod_cat_info as p on t.prod_cat_code=p.prod_cat_code
where Gender = 'M' and prod_cat = 'Electronics'
group by Gender,prod_cat,prod_subcat
order by [Total revenue]

--10.What is percentage of sales and returns by product sub category; display only top  5 sub categories in terms of sales? 

select top 5 Round(SUM(cast(total_amt as float)),2) as total_sales, P.prod_subcat from Transactions as T
INNER JOIN prod_cat_info as PON T.prod_subcat_code = P.prod_sub_cat_code
where T.Qty > 0
group by P.prod_subcat
order by total_sales desc

--11. For all customers aged between 25 to 35 years find what is the net total revenue  generated by these consumers in last 30 days of transactions from max transaction  date available in the data? 


select sum(cast(total_amt as float)) [net total revenue] from (select *, MAX(tran_date) over() [max transaction date] from transactions t) t 
left join customer c on t.cust_id = c.customer_id 
where tran_date >= DATEADD(day,-30, t.[max transaction date]) 
and tran_date >= DATEADD(year,25,dob) and tran_date< DATEADD(year,31,dob)

--12.Which product category has seen the max value of returns in the last 3 months of transactions? 

select * from prod_cat_info
select * from Transactions
select * from Customer

SELECT TOP 1 prod_cat_code,SUM(cast(total_amt as float)) as totalreturns FROM TRANSACTIONS
WHERE Tran_date >= DATEADD(day, -90, CONVERT(VARCHAR,'02/28/2014',103)) AND Total_amt < 0
GROUP BY prod_cat_code
ORDER BY totalreturns ASC

--13.Which store-type sells the maximum products; by value of sales amount and by quantity sold?  

select Store_type,(sum(CAST(qty as float)))[No of Products],sum(cast(total_amt as float))[sales amount] 
from transactions t left join prod_cat_info p on t.prod_cat_code = p.prod_cat_code and t.prod_subcat_code = p.prod_sub_cat_code
group by Store_type
order by (sum(CAST(qty as float))) desc, sum(cast(total_amt as float)) desc

--14.What are the categories for which average revenue is above the overall average.

select prod_cat [categories] , avg(cast(total_amt as float)) [avg revenue] from transactions t left join prod_cat_info p on t.prod_cat_code = p.prod_cat_code and t.prod_subcat_code = p.prod_sub_cat_code
group by prod_cat
having AVG(cast(total_amt as float)) > (select avg(cast(total_amt as float)) from transactions t left join prod_cat_info p on t.prod_cat_code = p.prod_cat_code and t.prod_subcat_code = p.prod_sub_cat_code)

--15. Find the average and total revenue by each subcategory for the categories which are among top 5 categories in terms of quantity sold.  

select P.prod_subcat as Product_SubCategory, AVG(cast(total_amt as float)) as Average_Revenue,SUM(cast(total_amt as float)) as Total_Revenue from Transactions 
as T INNER JOIN prod_Cat_info as P ON T.prod_cat_code = P.prod_cat_code AND T.prod_subcat_code = P.prod_sub_cat_code
group by P.prod_subcat






